name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Service container for PostgreSQL
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: blog_api_spring
          POSTGRES_USER: ohmu
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/blog_api_spring
          SPRING_DATASOURCE_USERNAME: ohmu
          SPRING_DATASOURCE_PASSWORD: password